apiVersion: v1
kind: ServiceAccount
metadata:
  name: derhuerst-service-account
  namespace: derhuerst
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-derhuerst-rb
  namespace: derhuerst
subjects:
- kind: User
  name: derhuerst
  apiGroup: ""
- kind: ServiceAccount
  name: derhuerst
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-logs-derhuerst-rb
  namespace: kube-logging
subjects:
- kind: User
  name: derhuerst
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-logs-derhuerst-rb
  namespace: kube-logging
subjects:
- kind: User
  name: derhuerst
  apiGroup: ""
roleRef:
  kind: Role
  name: log-port-forward
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: derhuerst
  name: derhuerst-ci-role
rules:
- apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
  resources: ["services", "deployments", "ingresses"]
  verbs: ["create", "update", "patch", "list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: derhuerst-ci-rb
  namespace: derhuerst
subjects:
- kind: User
  name: derhuerst-ci
  apiGroup: ""
roleRef:
  kind: Role
  name: derhuerst-ci-role
  apiGroup: ""
---
