apiVersion: v1
clusters:
- name: foss-cluster
  cluster:
    certificate-authority-data: <CA>
    server: <SERVER>
contexts:
- name: <USER>@foss-cluster
  context:
    cluster: foss-cluster
    user: <USER>
    namespace: <NAMESPACE>
current-context: <USER>@foss-cluster
kind: Config
preferences: {}
users:
- name: <USER>
  user:
    client-key-data: <KEY>
    client-certificate-data: <CERTIFICATE>
